### ISSUE TITLE
Weird data

### ISSUE THREAD

**Issue by rucksman** [kettenbach-it/FHEM-SMA-Speedwire#3]
I tried the smaem_test.pl with my Sunny Boy 3600 Smart Energy combined with an Energy Meter and a Home Manager. My first goal was only to get some data out of the inverter or the Ebergy Meter, but why not learning FHEM at the same time? My Problem: When the scripts starts, it takes ages until some output can be seen on the terminal. And when there is finally an output, the data s totally weird, and after the last line nothing happens, only Control-C stops the script.

L1:
        Bezug Wirkleistung (W): 0.0
        Bezug Wirkleistung Zähler (kWh): 0.0
        Einspeisung Wirkleistung (W): 0.0
        Einspeisung Wirkleistung Zähler (kWh): 0.0

        Bezug Blindleistung (var): 0.0
        Bezug Blindleistung Zähler (kvarh): 0.0
        Einspeisung Blindleistung (var): 0.0
        Einspeisung Blindleistung Zähler (kvarh): 0.0

        Bezug Scheinleistung (VA): 0.0
        Bezug Scheinleistung Zähler (kVAh): 0.0
        Einspeisung Scheinleistung (VA): 0.0
        Einspeisung Scheinleistung Zähler (kVAh): 0.0

        CosPhi: 0.000
        THD: 0.00
        Spannung (V): 0.0
L2:
        Bezug Wirkleistung (W): 0.0
        Bezug Wirkleistung Zähler (kWh): 0.0
        Einspeisung Wirkleistung (W): 0.0
        Einspeisung Wirkleistung Zähler (kWh): 0.0

        Bezug Blindleistung (var): 0.0
        Bezug Blindleistung Zähler (kvarh): 0.0
        Einspeisung Blindleistung (var): 0.0
        Einspeisung Blindleistung Zähler (kvarh): 0.0

        Bezug Scheinleistung (VA): 0.0
        Bezug Scheinleistung Zähler (kVAh): 0.0
        Einspeisung Scheinleistung (VA): 0.0
        Einspeisung Scheinleistung Zähler (kVAh): 0.0

        CosPhi: 0.000
        THD: 0.00
        Spannung (V): 0.0
L3:
        Bezug Wirkleistung (W): 0.0
        Bezug Wirkleistung Zähler (kWh): 0.0
        Einspeisung Wirkleistung (W): 0.0
        Einspeisung Wirkleistung Zähler (kWh): 0.0

        Bezug Blindleistung (var): 0.0
        Bezug Blindleistung Zähler (kvarh): 0.0
        Einspeisung Blindleistung (var): 0.0
        Einspeisung Blindleistung Zähler (kvarh): 0.0

        Bezug Scheinleistung (VA): 0.0
        Bezug Scheinleistung Zähler (kVAh): 0.0
        Einspeisung Scheinleistung (VA): 0.0
        Einspeisung Scheinleistung Zähler (kVAh): 0.0

        CosPhi: 0.000
        THD: 0.00
        Spannung (V): 0.0

Alle Phasen:
        Bezug Wirkleistung (W): 86310912.0
        Bezug Wirkleistung Zähler (kWh): 30024305321.8
        Einspeisung Wirkleistung (W): 0.3
        Einspeisung Wirkleistung Zähler (kWh): 0.0

        Bezug Blindleistung (var): 86310912.0
        Bezug Blindleistung Zähler (kvarh): 0.0
        Einspeisung Blindleistung (var): 0.0
        Einspeisung Blindleistung Zähler (kvarh): 0.0

        Bezug Scheinleistung (VA): 0.0
        Bezug Scheinleistung Zähler (kVA): 0.0
        Einspeisung Scheinleistung (VA): 0.0
        Einspeisung Scheinleistung Zähler (kVA): 0.0

        CosPhi: 0.000

Plausichecks:
        Bezug Wirkleistung: 0.0 + 0.0 + 0.0 = 0 ? == 86310912.0
        Bezug Wirkleistung Zähler: 0.0 + 0.0 + 0.0 = 0 ?== 30024305321.8

        Einspeisung Wirkleistung: 0.0 + 0.0 + 0.0 = 0 ? == 0.3
        Bezug Wirkleistung Zähler: 0.0 + 0.0 + 0.0 = 0 ?== 0.0

        Einspeisung Leistung 0.3 + 0.0 = 0.3 ?== 0.0
        Bezug Leistung 86310912.0 + 86310912.0 = 172621824 ?== 0.0

**Comment by kettenbach-it** [comment]
Most likely, your computer and/or network does not support multicast transmissions.
The script ist waiting for ages and nothing comes in. The data displayed is probably just random crap.
Please check your computer and network for proper multicast routing.
Since this is not an issue of the software, I'll close this issue.
For further support, please use http://forum.fhem.de
