### ISSUE TITLE
Monatsertrag anzeigen lassen und Temp bei STP 5.0 3AV

### ISSUE THREAD

**Issue by oligraf** [kettenbach-it/FHEM-SMA-Speedwire#4]
Hallo,

erst mal finde ich es super das es solche OpenSource Software gibt.

Ich habe SMAInverter und SMAEM in FEHM laufen.
Läuft beides auch soweit ganz ordentlich.

Falls es möglich ist, wäre es schön wenn auch die Monatserträge, bzw beim EnergyMeter  Bezug und Einspeisung per Monat angezeigt werden könnte.

-

Ich habe 2 SMA WR einen STP 10000 TL10 mit Speedwire Schnittstelle und einen STP 5.0 3AV
bei dem STP10000 wird die Temperatur angezeigt, beim STP 5.0 nicht. Parallel betreibe ich noch SolarView, dort ist es genau anders herum, woran könnte das liegen.

Danke.

Gruß Oliver

**Comment by kettenbach-it** [comment]
Hallo Oliver,

bitte Stelle diese Frage im Forum:

https://forum.fhem.de/index.php/topic,56080.0.html
